// db/seed.js -- populates the MongoDB challenge catalog. Idempotent (safe
// to re-run; upserts by slug).
require("dotenv").config();
const crypto = require("crypto");
const { connectMongo, mongoose } = require("./mongo");
const Challenge = require("../models/Challenge");

function flagHash(flag) {
  return crypto.createHash("sha256").update(flag.trim()).digest("hex");
}

const challenges = [
  // ---------------- SQL Injection ----------------
  { slug: "sqli-login", title: "Authentication Bypass via SQL Injection", domain: "SQL Injection", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Easy", points: 100, color: "rose", summary: "The staff login builds its query with string concatenation.", briefing: "ClientPortal Inc.'s admin login concatenates input directly into SQL. Log in as admin without knowing the password.", flag: "ZDS{sql1_4uth_byp4ss_c0ncat3nat10n}", labPath: "/labs/sqli-login" },
  { slug: "sqli-union", title: "UNION-Based SQL Injection", domain: "SQL Injection", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Medium", points: 200, color: "rose", summary: "A category search lets you UNION in rows from an unrelated table.", briefing: "The product search query has a known column count. Append a UNION SELECT to pull secrets from a different table entirely.", flag: "ZDS{un10n_b4s3d_sql1_3xtr4ct5_4ny_t4bl3}", hint: "the query selects exactly 3 columns (name, category, price) from <code>sqli_products</code>. A UNION SELECT against a differently-named table (<code>sqli_secrets</code> has columns <code>id, label, value</code>) with a matching column count will surface its rows in this same table.", labPath: "/labs/sqli-union" },
  { slug: "sqli-blind-boolean", title: "Boolean-Based Blind SQL Injection", domain: "SQL Injection", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Hard", points: 300, color: "rose", summary: "An order lookup only reveals found/not-found -- extract data blind.", briefing: "No data is ever printed directly, only a boolean found/not-found oracle. Use it to extract a secret string one character at a time.", flag: "ZDS{bl1nd_b00l34n_sql1_1s_sl0w_but_sur3}", labPath: "/labs/sqli-blind-boolean" },
  { slug: "sqli-time-blind", title: "Time-Based Blind SQL Injection", domain: "SQL Injection", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Insane", points: 400, color: "rose", summary: "No oracle at all -- only response timing reveals anything.", briefing: "Not even a boolean signal is available. Use a conditional expensive query to create a measurable timing side-channel against the real database.", flag: "ZDS{t1m3_b4s3d_bl1nd_sql1_us3s_d3l4ys}", labPath: "/labs/sqli-time-blind" },

  // ---------------- Cross-Site Scripting ----------------
  { slug: "reflected-xss", title: "Reflected XSS in Search", domain: "Cross-Site Scripting", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Easy", points: 100, color: "fuchsia", summary: "A search page echoes your query straight back, unescaped.", briefing: "Craft a payload that executes JavaScript in the page and reads the non-HttpOnly cookie holding the flag.", flag: "ZDS{r3fl3ct3d_xss_1s_st1ll_ev3rywh3r3}", hint: "the app has set a non-HttpOnly cookie called <code>session_debug_token</code>. If you can execute JavaScript here, you can read it via <code>document.cookie</code>.", labPath: "/labs/reflected-xss" },
  { slug: "dom-xss-hash", title: "DOM-Based XSS via URL Fragment", domain: "Cross-Site Scripting", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Medium", points: 200, color: "fuchsia", summary: "Client-side JS writes location.hash into innerHTML with no sanitization.", briefing: "The vulnerable code never touches the server -- it's pure client-side DOM manipulation of the URL fragment.", flag: "ZDS{d0m_xss_n3v3r_touch3s_th3_s3rv3r}", hint: "a flag lives in a non-HttpOnly cookie called <code>dom_xss_flag_token</code>. The greeting logic runs entirely client-side and never sends the fragment to the server -- view page source to see how <code>#</code> is read and inserted.", labPath: "/labs/dom-xss-hash" },
  { slug: "xss-filter-bypass", title: "XSS Filter Bypass", domain: "Cross-Site Scripting", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Medium", points: 250, color: "fuchsia", summary: "A naive blacklist strips <script> but nothing else.", briefing: "The filter only removes the literal string <script>. Find another tag or event handler it never considered.", flag: "ZDS{bl4ckl1st_f1lt3rs_4lw4ys_h4v3_g4ps}", hint: "the filter only strips the literal string <code>&lt;script&gt;</code>. It says nothing about other tags or event handler attributes. A non-HttpOnly cookie <code>filter_bypass_flag_token</code> holds the flag.", labPath: "/labs/xss-filter-bypass" },
  { slug: "stored-xss", title: "Stored XSS in Comments", domain: "Cross-Site Scripting", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Hard", points: 350, color: "fuchsia", summary: "A public comment box renders input unescaped for every visitor.", briefing: "Post a payload that, when a simulated moderator bot views the page, exfiltrates its session token to your endpoint.", flag: "ZDS{st0r3d_xss_h4rv3sts_admin_s3ss10ns}", labPath: "/labs/stored-xss" },
  { slug: "svg-upload-xss", title: "Stored XSS via SVG Upload", domain: "Cross-Site Scripting", category: "Injection", owaspRef: "A03:2021 - Injection", difficulty: "Hard", points: 350, color: "fuchsia", summary: "SVG is XML -- and XML can contain <script>.", briefing: "Upload an SVG whose embedded script executes when opened directly (not via <img>), then read the flag from a same-origin cookie.", flag: "ZDS{svg_upl04ds_ar3_x_ss_1n_d1sgu1s3}", hint: "opening an SVG directly (not via <code>&lt;img&gt;</code>) renders it as its own document and executes any <code>&lt;script&gt;</code> inside it, same-origin. A flag lives in a non-HttpOnly cookie <code>gallery_secret</code> on this page's origin.", labPath: "/labs/svg-upload-xss" },

  // ---------------- Broken Access Control ----------------
  { slug: "idor-invoices", title: "IDOR: Anyone's Invoice Is Your Invoice", domain: "Broken Access Control", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Easy", points: 150, color: "amber", summary: "Invoices are fetched by a sequential ID with no ownership check.", briefing: "Walk the ID space to find an invoice that isn't yours.", flag: "ZDS{1d0r_numb3rs_d0nt_l13_4bout_0wn3rsh1p}", labPath: "/labs/idor-invoices" },
  { slug: "horizontal-privesc", title: "Horizontal Privilege Escalation", domain: "Broken Access Control", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Easy", points: 150, color: "amber", summary: "Read another user's private note by changing a username in the URL.", briefing: "You're logged in as alice. The notes endpoint trusts whatever username is in the URL.", flag: "ZDS{h0r1z0nt4l_pr1v3sc_1gn0r3s_0wn3rsh1p}", hint: "the notes endpoint takes a username directly in the URL. Nothing checks it against your own session.", labPath: "/labs/horizontal-privesc" },
  { slug: "forced-browse-admin", title: "Forced Browsing to a Hidden Admin Panel", domain: "Broken Access Control", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Easy", points: 150, color: "amber", summary: "An admin panel exists with zero authentication, just no visible link.", briefing: "Nothing links to the admin panel from the UI. That's not the same as it being protected.", flag: "ZDS{f0rc3d_br0ws1ng_h1dd3n_1s_n0t_pr0t3ct3d}", hint: "check <code>/robots.txt</code>-style hidden paths, common admin path wordlists, or view page source/JS bundles for hardcoded references to an admin route.", labPath: "/labs/forced-browse-admin" },
  { slug: "vertical-privesc", title: "Vertical Privilege Escalation", domain: "Broken Access Control", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Medium", points: 250, color: "amber", summary: "A logged-in 'user' role can call an admin-only action directly.", briefing: "The admin action isn't linked in the UI for a user role -- but the server never actually checks your role.", flag: "ZDS{v3rt1c4l_pr1v3sc_h1dd3n_1sn7_pr0t3ct3d}", hint: "try issuing <code>POST /labs/vertical-privesc/admin/grant-flag</code> directly (e.g. via curl, Postman, or your browser devtools Network/Console tab) even though nothing in the UI links to it.", labPath: "/labs/vertical-privesc" },
  { slug: "mass-assignment-role", title: "Mass Assignment to Admin Role", domain: "Broken Access Control", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Medium", points: 250, color: "amber", summary: "A profile update endpoint merges your entire JSON body, unfiltered.", briefing: "Only displayName is exposed in the UI form. What other fields does the endpoint actually accept?", flag: "ZDS{m4ss_4ss1gnm3nt_tru5ts_ev3ry_f13ld}", hint: "only <code>displayName</code> is exposed in the UI form, but the endpoint merges whatever JSON keys you send. What happens if you add a <code>\"role\":\"admin\"</code> field?", labPath: "/labs/mass-assignment-role" },
  { slug: "file-access-idor", title: "IDOR on File Downloads", domain: "Broken Access Control", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Medium", points: 250, color: "amber", summary: "Reports are fetched by a predictable ID with no ownership check.", briefing: "Report IDs sit right next to your own files. Nearby documents were inserted moments apart.", flag: "ZDS{f1l3_id0r_s3qu3nt14l_1ds_l34k}", hint: "report IDs are just MongoDB ObjectIds shown right next to each of your own files. Nearby documents were inserted moments apart -- try IDs adjacent to your own.", labPath: "/labs/file-access-idor" },

  // ---------------- CSRF ----------------
  { slug: "csrf-email-change", title: "CSRF: Silent Email Takeover", domain: "CSRF", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Medium", points: 200, color: "red", summary: "The email-change form has no CSRF token.", briefing: "Build an auto-submitting exploit page and trigger a simulated victim to visit it.", flag: "ZDS{csrf_t0k3ns_ar3nt_0pt10nal}", labPath: "/labs/csrf-email-change" },
  { slug: "csrf-get-based", title: "CSRF via State-Changing GET", domain: "CSRF", category: "Broken Access Control", owaspRef: "A01:2021", difficulty: "Easy", points: 150, color: "red", summary: "A funds transfer is wired to a plain GET request.", briefing: "A bare <img> tag on any page would trigger this. No click, no JS, no form needed.", flag: "ZDS{g3t_r3qu3sts_sh0uld_n3v3r_ch4ng3_st4t3}", hint: "the transfer endpoint is a GET request with no CSRF token. A page hosted anywhere else containing <code>&lt;img src=\"/labs/csrf-get-based/transfer?to=attacker&amp;amount=500\"&gt;</code> would trigger it automatically for a logged-in victim who merely visits that page. Try it by pasting that URL directly into a new tab (simulating the forced navigation).", labPath: "/labs/csrf-get-based" },

  // ---------------- Command Injection ----------------
  { slug: "cmd-injection", title: "OS Command Injection in Ping Tool", domain: "Command Injection", category: "Injection", owaspRef: "A03:2021", difficulty: "Medium", points: 250, color: "orange", summary: "A diagnostics tool shells out to ping with unsanitized input.", briefing: "Break out of the intended ping argument and read a local flag file.", flag: "ZDS{n3v3r_sh3ll_0ut_w1th_us3r_1nput}", hint: "a flag file lives at <code>flag.txt</code> in this tool's working directory. The server builds a shell command with your input directly in it.", labPath: "/labs/cmd-injection" },

  // ---------------- SSRF ----------------
  { slug: "ssrf-metadata", title: "SSRF to Cloud Metadata Service", domain: "SSRF", category: "SSRF", owaspRef: "A10:2021", difficulty: "Hard", points: 350, color: "cyan", summary: "An avatar-from-URL importer fetches any URL, server-side.", briefing: "A simulated internal metadata endpoint holds a secret. Get the server to fetch it for you.", flag: "ZDS{ssrf_turns_s3rv3rs_1nto_pr0xy_puppets}", hint: "this environment simulates a cloud metadata service reachable only from inside the network, at <code>http://169.254.169.254/</code>. The importer has no allowlist on which hosts it will fetch.", labPath: "/labs/ssrf-metadata" },
  { slug: "ssrf-webhook", title: "SSRF via Webhook Tester", domain: "SSRF", category: "SSRF", owaspRef: "A10:2021", difficulty: "Hard", points: 350, color: "cyan", summary: "A 'test your webhook' feature reaches an internal-only admin API.", briefing: "The webhook tester fetches whatever URL you give it. What's reachable that shouldn't be?", flag: "ZDS{ssrf_w3bh00ks_r34ch_1nt3rn4l_4p1s}", hint: "this environment simulates an internal-only admin API reachable at <code>http://internal-admin.local/</code>, with an endpoint at <code>/internal/admin/flag</code>.", labPath: "/labs/ssrf-webhook" },
  { slug: "ssrf-pdf-generator", title: "SSRF via PDF Generation", domain: "SSRF", category: "SSRF", owaspRef: "A10:2021", difficulty: "Hard", points: 350, color: "cyan", summary: "An invoice PDF renderer fetches image sources server-side.", briefing: "Any <img src> in your invoice HTML is fetched by the SERVER while rendering, not your browser.", flag: "ZDS{ssrf_v14_pdf_r3nd3r3rs_1s_r34l}", hint: "this environment simulates an internal config file reachable only from the server at <code>http://pdf-internal.local/config</code>.", labPath: "/labs/ssrf-pdf-generator" },

  // ---------------- XXE ----------------
  { slug: "xxe-profile-import", title: "XXE via Profile Import", domain: "XXE", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Hard", points: 350, color: "lime", summary: "A profile importer parses XML with external entities enabled.", briefing: "Craft a DOCTYPE with a SYSTEM entity that reads a local file and gets reflected back.", flag: "ZDS{xxe_ext3rnal_ent1t13s_r3ad_l0cal_f1l3s}", hint: "a file at <code>secret.txt</code> sits in this app's working directory. A DTD with a <code>SYSTEM</code> entity referencing a local file, substituted into a field the app reflects back (like <code>displayName</code>), will read it.", labPath: "/labs/xxe-profile-import" },
  { slug: "xxe-svg-upload", title: "XXE via SVG Upload", domain: "XXE", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Hard", points: 350, color: "lime", summary: "SVG avatar processing resolves external entities too.", briefing: "SVG is XML. The same unsafe entity resolution as the profile importer, reached through an image upload.", flag: "ZDS{xxe_v14_svg_upl04d_r34ds_l0c4l_f1l3s}", hint: "a file <code>flag.txt</code> sits in this app's working directory. SVG is XML -- a DOCTYPE with a SYSTEM entity, referenced inside <code>&lt;title&gt;</code>, will be resolved and reflected back.", labPath: "/labs/xxe-svg-upload" },
  { slug: "xxe-oob-exfil", title: "Blind XXE via Out-of-Band Exfiltration", domain: "XXE", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Insane", points: 450, color: "lime", summary: "Nothing is reflected back -- exfiltrate data via a self-hosted DTD.", briefing: "Host your own malicious DTD, get the target to fetch it, and have it call your collector with a local file's contents.", flag: "ZDS{00b_xxe_3xf1ltr4t3s_v14_dtd_f3tch}", labPath: "/labs/xxe-oob-exfil" },

  // ---------------- SSTI ----------------
  { slug: "ssti-render", title: "Server-Side Template Injection", domain: "SSTI", category: "Injection", owaspRef: "A03:2021", difficulty: "Hard", points: 400, color: "purple", summary: "A greeting card generator renders your message as a template.", briefing: "Your message becomes part of the template source itself, not just its data. Escalate to calling a server-side function.", flag: "ZDS{ssti_turns_templat3s_1nto_c0de_ex3c}", hint: "the render step evaluates your message as part of a JS template literal. If you can get an arbitrary expression to execute, there's a <code>flag()</code> function in scope.", labPath: "/labs/ssti-render" },

  // ---------------- Insecure Deserialization ----------------
  { slug: "insecure-deserialization", title: "Insecure Deserialization in Session Cookie", domain: "Insecure Deserialization", category: "Software and Data Integrity Failures", owaspRef: "A08:2021", difficulty: "Hard", points: 400, color: "teal", summary: "A 'remember me' cookie is unsigned base64 JSON the server trusts on faith.", briefing: "Tamper with the deserialized object's role field to escalate privileges without ever logging in as admin.", flag: "ZDS{unsign3d_c00k1es_ar3_just_suggest10ns}", labPath: "/labs/insecure-deserialization" },

  // ---------------- Authentication ----------------
  { slug: "jwt-alg-none", title: "JWT 'alg:none' Authentication Bypass", domain: "Authentication", category: "Identification and Authentication Failures", owaspRef: "A07:2021", difficulty: "Hard", points: 400, color: "indigo", summary: "The API accepts alg:none tokens, skipping signature checks entirely.", briefing: "Edit the payload, set alg to none, strip the signature -- the API trusts it.", flag: "ZDS{alg_n0ne_m3ans_n0_v3r1f1cat10n_at_all}", hint: "the verifier trusts the token's own header. Try changing <code>alg</code> to <code>none</code>, editing the payload's <code>role</code> to <code>admin</code>, and removing the signature segment.", labPath: "/labs/jwt-alg-none" },
  { slug: "jwt-weak-secret", title: "JWT Signed with a Weak Secret", domain: "Authentication", category: "Identification and Authentication Failures", owaspRef: "A07:2021", difficulty: "Hard", points: 400, color: "indigo", summary: "Signature verification is real -- but the HMAC secret is guessable.", briefing: "Crack the weak secret, then forge your own valid admin token.", flag: "ZDS{w34k_jwt_s3cr3ts_ar3_brut3f0rc34bl3}", hint: "copy the token to jwt.io (or a local tool), and try cracking the HMAC secret against a short common-password wordlist (think: something a lazy developer would type as a placeholder secret). Once cracked, forge a token with <code>role: \"admin\"</code> signed with that secret.", labPath: "/labs/jwt-weak-secret" },
  { slug: "broken-password-reset", title: "Predictable Password Reset Tokens", domain: "Authentication", category: "Identification and Authentication Failures", owaspRef: "A07:2021", difficulty: "Medium", points: 300, color: "indigo", summary: "Reset tokens are a sequential counter, not cryptographically random.", briefing: "Request your own reset to learn the token format, then predict another account's token.", flag: "ZDS{pr3d1ct4bl3_r3s3t_t0k3ns_l34k_4cc0unts}", hint: "request a reset for your own <code>guest</code> account first to see the token format (e.g. <code>RST-1001</code>). Then request a reset for <code>admin</code> too -- the email \"sends\" silently, but the token is still just the next number in the same sequence. Guess it and complete the reset.", labPath: "/labs/broken-password-reset" },
  { slug: "account-enum-timing", title: "User Enumeration via Timing Side-Channel", domain: "Authentication", category: "Identification and Authentication Failures", owaspRef: "A07:2021", difficulty: "Insane", points: 450, color: "indigo", summary: "Identical error messages, but real bcrypt timing leaks valid usernames.", briefing: "The message never changes -- but response time does, because hashing only runs for real accounts.", flag: "ZDS{t1m1ng_s1d3_ch4nn3ls_l34k_us3rn4m3s}", hint: "the error message never changes, but real password hashing only happens for real usernames. Compare response times for <code>admin</code> vs. a random username -- the difference is genuine and measurable (check your browser's Network tab timing).", labPath: "/labs/account-enum-timing" },
  { slug: "no-rate-limit-bruteforce", title: "Missing Rate Limiting on PIN Login", domain: "Authentication", category: "Identification and Authentication Failures", owaspRef: "A07:2021", difficulty: "Easy", points: 150, color: "indigo", summary: "A 4-digit PIN with 10,000 combos and zero throttling.", briefing: "No lockout, no CAPTCHA, no delay. Automate it.", flag: "ZDS{n0_r4t3_l1m1t_m34ns_10000_tr13s_ar3_fr33}", hint: "there are only 10,000 possible 4-digit PINs, and this endpoint has no rate limiting, lockout, or CAPTCHA. A simple script (curl loop, Burp Intruder, etc.) posting <code>pin=0000</code> through <code>pin=9999</code> to <code>POST /labs/no-rate-limit-bruteforce/try-pin</code> will find it.", labPath: "/labs/no-rate-limit-bruteforce" },
  { slug: "two-factor-bypass", title: "2FA Logic Bypass", domain: "Authentication", category: "Identification and Authentication Failures", owaspRef: "A07:2021", difficulty: "Medium", points: 300, color: "indigo", summary: "A leftover client-trusted field skips real OTP verification.", briefing: "Inspect what the OTP verification request actually sends. Is there another field the client code is capable of adding?", flag: "ZDS{2f4_l0g1c_fl4ws_tru5t_th3_cl13nt}", hint: "inspect the request the OTP form sends (Network tab). Is there any other field the client-side code might be capable of sending alongside <code>otp</code>?", labPath: "/labs/two-factor-bypass" },

  // ---------------- NoSQL Injection ----------------
  { slug: "nosql-login-bypass", title: "NoSQL Injection: Login Bypass", domain: "NoSQL Injection", category: "Injection", owaspRef: "A03:2021", difficulty: "Medium", points: 250, color: "green", summary: "A JSON login body lets you send operators instead of strings.", briefing: "The password field is dropped straight into a real MongoDB query filter. What happens if it's an object, not a string?", flag: "ZDS{n0sql_0p3r4t0r_1nj3ct10n_byp4ss3s_l0g1n}", hint: "the query is <code>LabAccount.findOne({ username, password })</code> executed against a real database. JSON lets you send <code>password</code> as an object instead of a string -- what does MongoDB do with <code>{\"$ne\": null}</code> there?", labPath: "/labs/nosql-login-bypass" },
  { slug: "nosql-search-injection", title: "NoSQL Injection: Query-String Operators", domain: "NoSQL Injection", category: "Injection", owaspRef: "A03:2021", difficulty: "Medium", points: 250, color: "green", summary: "Bracket-notation query params merge straight into a Mongo filter.", briefing: "Express parses ?field[$op]=value into a nested object automatically. What does that do to a hidden 'released' filter?", flag: "ZDS{n0sql_qu3rystr1ng_0p3r4t0r_1nj3ct10n}", labPath: "/labs/nosql-search-injection" },
  { slug: "nosql-regex-extraction", title: "NoSQL Injection: Blind $regex Extraction", domain: "NoSQL Injection", category: "Injection", owaspRef: "A03:2021", difficulty: "Hard", points: 350, color: "green", summary: "A pattern-check endpoint passes your input straight into $regex.", briefing: "Anchored regex probes let you extract a secret value one character at a time, purely from a match/no-match response.", flag: "ZDS{r3g3x_1nj3ct10n_l34ks_byt3_by_byt3}", hint: "try anchored patterns like <code>^Z</code>, then <code>^ZD</code>, then <code>^ZDS</code>... extending one character at a time confirms each next character of the real stored code.", labPath: "/labs/nosql-regex-extraction" },
  { slug: "nosql-expr-injection", title: "NoSQL Injection: $expr Aggregation Abuse", domain: "NoSQL Injection", category: "Injection", owaspRef: "A03:2021", difficulty: "Insane", points: 450, color: "green", summary: "A raw filter fragment is merged into a real query, $expr included.", briefing: "MongoDB's aggregation expression language lets you build arbitrary boolean conditions against fields the API never exposes.", flag: "ZDS{3xpr3ss10n_1nj3ct10n_v14_expr_0p3r4t0r}", hint: "MongoDB's <code>$expr</code> lets you write aggregation expressions inside a query filter, e.g.:", labPath: "/labs/nosql-expr-injection" },

  // ---------------- Prototype Pollution ----------------
  { slug: "prototype-pollution", title: "Prototype Pollution to Privilege Escalation", domain: "Prototype Pollution", category: "Software and Data Integrity Failures", owaspRef: "A08:2021", difficulty: "Insane", points: 500, color: "violet", summary: "A recursive merge reaches __proto__ with no key filtering.", briefing: "Pollute the prototype chain to flip an isAdmin check that every request implicitly trusts.", flag: "ZDS{__proto__pollut10n_p01s0ns_ev3ry_0bj3ct}", hint: "the merge function recurses into nested objects with no key filtering. What happens if your JSON includes a <code>__proto__</code> key with <code>{\"isAdmin\": true}</code> inside it?", labPath: "/labs/prototype-pollution" },

  // ---------------- API Security ----------------
  { slug: "api-excessive-data", title: "API: Excessive Data Exposure", domain: "API Security", category: "API Security", owaspRef: "OWASP API3:2019", difficulty: "Easy", points: 150, color: "sky", summary: "The API returns the full backing document, not just safe fields.", briefing: "The UI card only shows name and title. What does the raw JSON response actually contain?", flag: "ZDS{3xc3ss1v3_d4t4_3xp0sur3_tru5ts_th3_fr0nt3nd}", labPath: "/labs/api-excessive-data" },
  { slug: "api-bola", title: "API: Broken Object Level Authorization", domain: "API Security", category: "API Security", owaspRef: "OWASP API1:2019", difficulty: "Medium", points: 250, color: "sky", summary: "The orders API trusts the :id in the URL with no ownership check.", briefing: "Order IDs are sequential. The API never checks who's asking.", flag: "ZDS{4p1_b0l4_1s_1d0r_w34r1ng_4_su1t}", hint: "order IDs are sequential (<code>ord_1001</code>, <code>ord_1002</code>, ...). The API never checks that the order you're requesting belongs to you.", labPath: "/labs/api-bola" },
  { slug: "api-mass-assignment", title: "API: Mass Assignment on PATCH", domain: "API Security", category: "API Security", owaspRef: "OWASP API6:2019", difficulty: "Medium", points: 250, color: "sky", summary: "A PATCH endpoint merges the entire request body, unfiltered.", briefing: "The UI only ever PATCHes displayName. The API itself accepts anything.", flag: "ZDS{4p1_m4ss_4ss1gnm3nt_uns3t_t13rs}", hint: "the UI only ever sends <code>displayName</code>, but the API itself accepts anything. What happens if you PATCH with <code>{\"accountTier\":\"enterprise\"}</code>?", labPath: "/labs/api-mass-assignment" },
  { slug: "graphql-introspection", title: "GraphQL Introspection Enabled", domain: "API Security", category: "API Security", owaspRef: "OWASP API9:2019", difficulty: "Medium", points: 250, color: "sky", summary: "Introspection reveals fields never used by any real client.", briefing: "Query __schema to see every field the API exposes, including undocumented ones.", flag: "ZDS{gr4phql_1ntr0sp3ct10n_l34ks_h1dd3n_f13lds}", hint: "introspection is enabled. Try querying <code>{ __schema { fields { name description } } }</code> to see every field the schema exposes, including ones never used by the actual UI.", labPath: "/labs/graphql-introspection" },

  // ---------------- Business Logic ----------------
  { slug: "logic-negative-quantity", title: "Business Logic: Negative Quantity", domain: "Business Logic", category: "Business Logic", owaspRef: "OWASP Top 10 (Logic Flaws)", difficulty: "Easy", points: 150, color: "orange", summary: "Checkout accepts negative quantities with no lower bound.", briefing: "Quantity times price, no validation on the sign.", flag: "ZDS{n3g4t1v3_qu4nt1ty_turns_purch4s3s_1nt0_r3funds}", hint: "quantity is never checked for being non-negative before the price is calculated.", labPath: "/labs/logic-negative-quantity" },
  { slug: "logic-price-tampering", title: "Business Logic: Client-Trusted Price", domain: "Business Logic", category: "Business Logic", owaspRef: "OWASP Top 10 (Logic Flaws)", difficulty: "Easy", points: 150, color: "orange", summary: "A hidden form field carries the price the server actually charges.", briefing: "Find the hidden price field and edit the request before it reaches the server.", flag: "ZDS{cl13nt_pr1c3s_ar3_just_su663st10ns}", hint: "open devtools, find the hidden <code>price</code> field in this form, and edit it before submitting -- the request is what the server actually trusts.", labPath: "/labs/logic-price-tampering" },
  { slug: "logic-workflow-skip", title: "Business Logic: Skipping the Payment Step", domain: "Business Logic", category: "Business Logic", owaspRef: "OWASP Top 10 (Logic Flaws)", difficulty: "Medium", points: 250, color: "orange", summary: "The 'confirm order' step never checks that payment actually succeeded.", briefing: "Three steps exist in the UI. Does the server enforce that order, or just assume it?", flag: "ZDS{sk1pp3d_st3ps_st1ll_c0mpl3t3_th3_0rd3r}", hint: "the \"Pay\" button always declines on purpose. But is there anything stopping you from calling <code>POST /labs/logic-workflow-skip/confirm</code> directly, whether or not payment ever succeeded?", labPath: "/labs/logic-workflow-skip" },
  { slug: "logic-coupon-race", title: "Business Logic: Race Condition on Coupon Redemption", domain: "Business Logic", category: "Business Logic", owaspRef: "OWASP Top 10 (Logic Flaws)", difficulty: "Insane", points: 450, color: "orange", summary: "A single-use coupon can be redeemed more than once, concurrently.", briefing: "The redeem endpoint reads, waits, then writes -- not atomically. Fire several requests at once against the real database.", flag: "ZDS{r4c3_c0nd1t10ns_d0ubl3_sp3nd_c0up0ns}", hint: "the endpoint reads <code>usesRemaining</code>, waits, then writes the decrement -- not atomically. Sending several redeem requests at the same time can let more than one pass the check before any of them saves.", labPath: "/labs/logic-coupon-race" },

  // ---------------- File Upload ----------------
  { slug: "upload-content-type-bypass", title: "File Upload: Content-Type Allowlist Bypass", domain: "File Upload", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Medium", points: 250, color: "yellow", summary: "Only the client-declared Content-Type header is checked.", briefing: "Declare image/png but upload something else entirely -- served back by real extension, not declared type.", flag: "ZDS{c0nt3nt_typ3_ch3cks_ar3n7_c0nt3nt_v4l1d4t10n}", hint: "the server only checks the <code>X-Declared-Type</code> header you send, not the actual bytes. What happens if you declare <code>image/png</code> but name the file <code>x.html</code> with HTML/JS content inside? A flag lives in a non-HttpOnly cookie <code>upload_bypass_flag_token</code>.", labPath: "/labs/upload-content-type-bypass" },
  { slug: "upload-path-traversal", title: "File Upload: Path Traversal", domain: "File Upload", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Medium", points: 300, color: "yellow", summary: "The upload filename is joined onto a directory with no containment check.", briefing: "A crafted filename can write outside the intended uploads folder entirely.", flag: "ZDS{p4th_tr4v3rs4l_3sc4p3s_th3_upl04ds_f0ld3r}", hint: "try a filename like <code>../protected/pwned.txt</code>.", labPath: "/labs/upload-path-traversal" },
  { slug: "upload-unrestricted-rce", title: "File Upload: Unrestricted Upload to Code Execution", domain: "File Upload", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Hard", points: 400, color: "yellow", summary: "Any file type is accepted, and 'plugins' get executed server-side.", briefing: "Upload a plugin file, then trigger it to run -- genuine server-side JS execution driven by your upload.", flag: "ZDS{unr3str1ct3d_upl04d_1s_r34l_c0d3_3x3c}", hint: "\"Run\" executes your uploaded file's JS server-side. A <code>reportFlag(value)</code> function is available in scope -- what value does it want?", labPath: "/labs/upload-unrestricted-rce" },

  // ---------------- Information Disclosure ----------------
  { slug: "disclosure-verbose-errors", title: "Verbose Error Messages", domain: "Information Disclosure", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Easy", points: 150, color: "slate", summary: "Unhandled exceptions return their full message and stack to the client.", briefing: "Trigger an unexpected input and see what the error response reveals about internal state.", flag: "ZDS{v3rb0s3_3rr0rs_l34k_1nt3rn4l_st4t3}", hint: "try submitting an empty ID, or a non-JSON string. What does the error response reveal?", labPath: "/labs/disclosure-verbose-errors" },
  { slug: "disclosure-env-file", title: "Exposed .env Configuration File", domain: "Information Disclosure", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Easy", points: 150, color: "slate", summary: "Static file serving exposes the app's own config directory.", briefing: "Try requesting the production .env file directly.", flag: "ZDS{3nv_f1l3_3xp0sur3_l34ks_ev3ryth1ng}", hint: "web servers often accidentally serve their own config directory. Try requesting <a class=\"lab-link\" href=\"/labs/disclosure-env-file/.env\">/labs/disclosure-env-file/.env</a>.", labPath: "/labs/disclosure-env-file" },
  { slug: "disclosure-backup-file", title: "Leftover Backup File Disclosure", domain: "Information Disclosure", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Easy", points: 150, color: "slate", summary: "An old .bak copy of a source file was left in the public directory.", briefing: "If billing.js exists, does billing.js.bak exist too, and get served just as plainly?", flag: "ZDS{b4ckup_f1l3s_l34v3_s3cr3ts_b3h1nd}", hint: "developers sometimes leave <code>.bak</code> copies next to the file they were editing. If <code>billing.js</code> exists, does <code>billing.js.bak</code> also exist and get served? Try <a class=\"lab-link\" href=\"/labs/disclosure-backup-file/billing.js.bak\">/labs/disclosure-backup-file/billing.js.bak</a>.", labPath: "/labs/disclosure-backup-file" },
  { slug: "disclosure-source-map", title: "Exposed Source Map", domain: "Information Disclosure", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Medium", points: 200, color: "slate", summary: "A production JS bundle ships with its source map still public.", briefing: "Reconstruct the original source from the .map file and look for anything that shouldn't have shipped.", flag: "ZDS{s0urc3_m4ps_l34k_0r1g1n4l_s0urc3}", hint: "minified bundles often reference a source map for debugging. Check the last line of the bundle, then fetch the <code>.map</code> file it points to and look inside <code>sourcesContent</code>.", labPath: "/labs/disclosure-source-map" },

  // ---------------- CORS & Headers ----------------
  { slug: "cors-wildcard-credentials", title: "Insecure CORS with Credentials", domain: "CORS & Headers", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Hard", points: 350, color: "blue", summary: "The API reflects any Origin and allows credentials.", briefing: "A page on any origin can read your authenticated API response. Try the simulated attacker page.", flag: "ZDS{r3fl3ct3d_c0rs_w1th_cr3d3nt14ls_l34ks_d4t4}", hint: "the API at <code>/labs/cors-wildcard-credentials/api/secret</code> reflects any <code>Origin</code> header with <code>Access-Control-Allow-Credentials: true</code>. Visit the simulated <a class=\"lab-link\" href=\"/labs/cors-wildcard-credentials/attacker-page\" target=\"_blank\">attacker page ↗</a> (imagine it hosted on evil.com) to see it read your full key cross-origin.", labPath: "/labs/cors-wildcard-credentials" },
  { slug: "clickjacking-missing-xfo", title: "Clickjacking via Missing Frame Protection", domain: "CORS & Headers", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Medium", points: 250, color: "blue", summary: "No X-Frame-Options or CSP frame-ancestors is set.", briefing: "The page can be framed invisibly and clicks stolen from an unsuspecting victim.", flag: "ZDS{cl1ckj4ck1ng_st34ls_r34l_cl1cks}", hint: "this page sets no <code>X-Frame-Options</code> or CSP <code>frame-ancestors</code>. Visit the <a class=\"lab-link\" href=\"/labs/clickjacking-missing-xfo/attacker-page\" target=\"_blank\">simulated attacker page ↗</a> and click \"Claim prize\" -- you're actually clicking the invisible delete button framed underneath.", labPath: "/labs/clickjacking-missing-xfo" },
  { slug: "crlf-header-injection", title: "CRLF Injection / Response Splitting", domain: "CORS & Headers", category: "Injection", owaspRef: "A03:2021", difficulty: "Insane", points: 450, color: "blue", summary: "A redirect target is written into a raw header with no CRLF stripping.", briefing: "Inject a CRLF sequence into the destination parameter to smuggle in extra response headers.", flag: "ZDS{crlf_1nj3ct10n_smuggl3s_h34d3rs}", hint: "try a <code>dest</code> value containing an encoded CRLF sequence (<code>%0d%0a</code>) followed by an extra header line, e.g. <code>%0d%0aSet-Cookie:%20pwned=1</code>, and inspect the raw response headers (curl -i or devtools Network tab, \"Response Headers\"). Confirm the injected header appears, then fetch <a class=\"lab-link\" href=\"/labs/crlf-header-injection/flag\" target=\"_blank\">/labs/crlf-header-injection/flag</a> for the flag.", labPath: "/labs/crlf-header-injection" },
  { slug: "host-header-poisoning", title: "Host Header Poisoning", domain: "CORS & Headers", category: "Security Misconfiguration", owaspRef: "A05:2021", difficulty: "Hard", points: 350, color: "blue", summary: "Password reset links are built from the incoming Host header.", briefing: "The Host header is just a request header -- fully attacker-controlled.", flag: "ZDS{h0st_h3ad3r_p01s0ns_r3s3t_l1nks}", hint: "the server trusts whatever <code>Host</code> header the request arrives with. Using devtools or curl, send the reset request with a forged <code>Host: evil-attacker.test</code> header and see what link gets generated.", labPath: "/labs/host-header-poisoning" }
];

async function seed() {
  await connectMongo();

  for (let i = 0; i < challenges.length; i++) {
    const c = challenges[i];
    await Challenge.updateOne(
      { slug: c.slug },
      {
        $set: {
          title: c.title, category: c.category, domain: c.domain, owaspRef: c.owaspRef,
          difficulty: c.difficulty, points: c.points, summary: c.summary, briefing: c.briefing,
          flagHash: flagHash(c.flag), labPath: c.labPath, color: c.color, orderIndex: i
        }
      },
      { upsert: true }
    );
  }

  console.log(`Seeded ${challenges.length} challenges.`);
  await mongoose.disconnect();
}

seed().catch(e => { console.error(e); process.exit(1); });
